dracor-org/dracor-frontend

package.json
src/components/DramaInfo/index.css
src/components/DramaInfo/index.js
src/components/SpeechDistribution.js
src/components/SpeechDistribution/Sapogov.js
src/components/SpeechDistribution/Yarkho.js
yarn.lock

Speech distribution charts

---

public/tei.css
src/components/DramaIndex/index.js

Render TEI documents

---

src/components/SpeechDistribution/Yarkho.js

Linear x-axis in Yarkho chart

---

package.json
src/App.js
src/components/TopNav.js
src/components/Yasgui.js
yarn.lock

Yes, YASGUI :)

---

package.json
src/App.js
src/components/APIDoc.js
src/components/TopNav.js
yarn.lock

Integrate Swagger UI

---

src/components/CorpusIndex.js
src/components/Home.js
src/components/IdLink.js
src/components/Play.css
src/components/Play.js
src/components/Years.js

This PR reorganises the page for individual plays adding meta data, download links and a tab rendering the TEI.
Resolves #60.

Restructure play page

---

package.json
src/CETEIcean.css
src/components/Play.css
src/components/Play.js
src/components/TEIPanel.js
yarn.lock

This PR replaces the styled XML in an iframe with a tree of custom HTML5 elements generated with [CETEIcean](https://github.com/TEIC/CETEIcean).

Render TEI with CETEIcean

---

src/components/CorpusIndex.js

Just testing the new (proper) feature branch workflow.

Open new tab

---

src/components/Play.js
src/index.css
src/slick-theme.css

Fixed Safari play displaying issues
Fixed overlapping navigation arrows at smaller screens

Safari fix

---

src/index.css
src/slick.css

Adjust margins and header size

---

src/components/Home.js
src/components/Metrics.js
src/index.css
src/slick-theme.css

Adjusts slider carousel resizing, and versioning information on smaller screens

Slider carousel adjustments

---

package.json
src/components/Play.js
src/components/TopNav.js
src/index.css
yarn.lock

Demo of the initial sticky header implementation

Sticky header

---

src/App.js
src/components/CorporaDropdown.js
src/components/Play.js
src/components/TopNav.js
src/components/TopNavDropdown.js
src/index.css

This PR adds new navigation dropdowns to resolve #111.

Restructure main navigation

---

public/cite_dracor.bib
public/cite_dracor.ris
src/components/Footer.js
src/components/Home.js

Update citation statement

---

src/components/NetworkGraph.js
src/components/Play.js
src/index.css

Fixed overflow authors handling

Sticky header update

---

src/index.css

Fixes linear gradient to transparent color values in safari by providing solid colours.

Fix footer gradient bug for iOS

---

src/components/Corpus.js
src/components/CorpusIndex.js
src/components/Play.js

Adjustments to modified author information from API (see dracor-org/dracor-api#119 and dracor-org/dracor-api#127).

Author name adjustments

---

src/components/CorpusLabel.js
src/components/CorpusLabel.module.scss
src/components/Play.js
src/index.scss

The idea is to make the _Name_ DraCor label reusable in other places.

Implement CorpusLabel component

---

src/components/CorpusLabel.module.scss
src/components/PlayDetailsHeader.js
src/components/PlayDetailsHeader.module.scss

This is an initial implementation of enriched authors metadata (with placeholders).

10 author images

---

src/components/Footer.module.scss
src/components/Header.module.scss
src/components/PlayDetailsHeader.module.scss
src/components/PlayDetailsTab.module.scss
src/components/TopNav.js
src/components/TopNav.module.scss
src/index.scss

This PR reintroduces the Headroom component for handling of long scrolling scenarios.

Headroom reintroduction

---

src/components/Play.js
src/network.js

Adjust node shapes and colors

---

src/components/Segments.tsx

Add heading to Segments component

---

src/components/CorpusIndex.js
src/components/CorpusIndex.scss
src/components/CorpusLabel.module.scss
src/components/IdLink.module.scss
src/components/PlayDetailsHeader.js
src/components/PlayDetailsHeader.module.scss
src/index.scss

This PR adds icons to Wikidata labels in corpora indices. Fixes #108

108 icons for id links

---

src/index.scss

Set full text width to 100%

---

src/components/PlayDetailsHeader.module.scss
src/index.scss

Increase z-index of the navbar

---

src/CETEIcean.scss

Add styles for titlePage in full text view

---

src/components/TopNav.js
src/components/TopNav.module.scss
src/images/TEI-Logo.svg
src/index.scss

This PR adds a prize ribbon for the "Rahtz Prize 2022"  to the top navigation bar.

Rahtz Prize 2022

---

src/components/DownloadLinks.js

add GraphML to available formats to download social relations in Download tab.
should fix #245

added relations as graphml to download links component

---

src/components/CorpusIndex.js

See dracor-org/dracor-api@dcc64e260eb6a109571c5d8ac479dbbce8f5bbb0

Adjust to renamed year properties in dracor-api

---

.env
Dockerfile
README.md
nginx.conf
src/App.tsx
src/components/APIDoc.js
src/components/APIDoc.scss
src/components/AuthorInfo.js
src/components/Corpus.js
src/components/CorpusIndex.js
src/components/DownloadLinks.js
src/components/Play.js
src/components/PlayMetrics.js
src/components/TopNav.js
src/config.js
src/setupProxy.js

This PR collects the necessary adjustments for the upcoming version 1.0 of the DraCor API.

Adjustments to API v1 changes

---

.github/workflows/docker-publish.yml

Set up workflow to publish docker image on release

---

src/components/Odd.scss

This PR proposes an overflow fix for ODD tables.

Handle table overflow

---

src/components/Commit.module.scss
src/components/Commit.tsx
src/components/Corpora.js
src/components/CorpusCard.js
src/components/CorpusIndex.js

Add linked corpus git commit hashes

---

src/components/CastList.jsx
src/components/CastList.module.scss
src/components/CorpusIndex.jsx

This fixes the following issues:
resolve #207
resolve #208
resolve #209

Design fixes

---

package.json
src/App.tsx
src/components/CorpusRegistry.module.scss
src/components/CorpusRegistry.tsx
src/components/TopNav.jsx
yarn.lock

Implement page for corpus registry information

---

src/CETEIcean.css

Fix castGroup styling
